---
name: Lingua-Han-PinYin
version: 0.03
author:
  - 'Fayland, fayland@gmail.com'
abstract: Retrieve the Mandarin(PinYin) of Chinese character(HanZi).
license: perl
requires:
  Encode: 0
  File::Spec: 0
provides:
  Lingua::Han::PinYin:
    file: lib/Lingua/Han/PinYin.pm
    version: 0.03
generated_by: Module::Build version 0.2611
