--- #YAML:1.0
name:                Lingua-Han-PinYin
version:             0.13
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Spec:                    0
    Lingua::Han::Utils:            0.10
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
